
default:
	hugo server --navigateToChanged --buildDrafts --buildFuture --buildExpired --disableFastRender --noHTTPCache --bind 0.0.0.0

build:
	hugo --cleanDestinationDir --destination public

install:
	npm install